### ISSUE TITLE
Fix test_qm.py under hera_mc for whatever change happened.

### ISSUE THREAD

**Issue by david-deboer** [HERA-Team/hera_qm#100]
ERROR: test_ingest_metrics_file (hera_mc.tests.test_qm.TestQM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ddeboer/Documents/ubase/Projects/HERA/ops/hera_mc/hera_mc/tests/test_qm.py", line 206, in test_ingest_metrics_file
    self.test_session.ingest_metrics_file(filename, 'firstcal')
  File "/Users/ddeboer/Documents/ubase/Projects/HERA/ops/hera_mc/hera_mc/mc_session.py", line 975, in ingest_metrics_file
    d = metrics2mc(filename, ftype)
  File "/Users/ddeboer/miniconda2/lib/python2.7/site-packages/hera_qm-0.0.0-py2.7.egg/hera_qm/utils.py", line 286, in metrics2mc
    d['array_metrics'][met] = data['max_std']
KeyError: 'max_std'

**Comment by plaplant** [comment]
This was addressed in hera_mc PR #152 (https://github.com/HERA-Team/hera_mc/pull/152).
