### ISSUE TITLE
`firstcal_metrics`: `sklearn` computes `nan` when only 1 time integration

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_qm#111]
skip GP delay fit when only 1 time integration present. traceback below

```
firstcal_metrics_run.py --std_cut=0.5 --extension=.firstcal_metrics.json zen.2458100.64001.xx.HH.uv.first.calfits
invalid value encountered in true_divide
invalid value encountered in double_scalars
Traceback (most recent call last):
  File "/home/obs/anaconda/envs/RTP/bin/firstcal_metrics_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('hera-qm==1.0', 'firstcal_metrics_run.py')
  File "/home/obs/anaconda/envs/RTP/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/obs/anaconda/envs/RTP/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/home/obs/anaconda/envs/RTP/lib/python2.7/site-packages/hera_qm-1.0-py2.7.egg/EGG-INFO/scripts/firstcal_metrics_run.py", line 12, in <module>
    firstcal_metrics.firstcal_metrics_run(files, args, history)
  File "/home/obs/anaconda/envs/RTP/lib/python2.7/site-packages/hera_qm-1.0-py2.7.egg/hera_qm/firstcal_metrics.py", line 846, in firstcal_metrics_run
    fm = FirstCal_Metrics(filename)
  File "/home/obs/anaconda/envs/RTP/lib/python2.7/site-packages/hera_qm-1.0-py2.7.egg/hera_qm/firstcal_metrics.py", line 418, in __init__
    GP.fit(x, y)
  File "/home/obs/anaconda/envs/RTP/lib/python2.7/site-packages/sklearn/gaussian_process/gpr.py", line 181, in fit
    X, y = check_X_y(X, y, multi_output=True, y_numeric=True)
  File "/home/obs/anaconda/envs/RTP/lib/python2.7/site-packages/sklearn/utils/validation.py", line 576, in check_X_y
    dtype=None)
  File "/home/obs/anaconda/envs/RTP/lib/python2.7/site-packages/sklearn/utils/validation.py", line 453, in check_array
    _assert_all_finite(array)
  File "/home/obs/anaconda/envs/RTP/lib/python2.7/site-packages/sklearn/utils/validation.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by adampbeardsley** [comment]
bump @nkern
